#include "Adehrents.h"




void Adehrents::inscription()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009AD begin
{
}
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009AD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adehrents::desinscription()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009AF begin
{
}
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adehrents::Emprunter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009BA begin
{
}
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009BA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Adehrents::Restituer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009BC begin
{
}
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009BC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
