#include "Livres.h"




void Livres::Empruntable()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009C8 begin
{
}
// section -64--88-56-1-313d700b:16f04d7fd4a:-8000:00000000000009C8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
